#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#232C31FF'  # default
T='#9EA7A6FF'   # text
W='#880000bb'  # wrong
V='#427D9E' # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--time-str="%l:%M:%S"  \
--date-str="%A, %d/%m/%Y" \
